# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CQUEST example

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

env:
  VIP_API_KEY: ${{ secrets.VIP_API_KEY }}

jobs:
  cquest-example_VipCI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f examples/cquest/requirements.txt ]; then pip install -r examples/cquest/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run the example
      run: |
        echo ${{ secrets.VIP_API_KEY }}
        python examples/cquest/example_VipCI.py
